language: objective-c
osx_image: xcode10.1
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - gem install xcpretty-travis-formatter
  - pod repo update
  - touch /tmp/DontPlay
script:
  - ./travis-build.sh
notifications:
  email:
    recipients:
      - noam.tamim@kaltura.com
      - nilit.danan@kaltura.com
      - gilad.nadav@kaltura.com
    on_success: change
    on_failure: always
